---
output: pdf_document
---
# Overall

* Removed 'Paper x' prefix for all the chapters.

* Merged the content on Self-assessment in TI (formerly known as Chapter 8) into the introduction: "1.3 Benchmarking computational tools".

* Fixed many typo's and grammatical errors.

# Chapter 1: introduction

* Added overview figure to section 1.2 of the types of analyses and applications enabled by single-cell omics. For each of the types of analyses, the applications are discussed in more detailed in the respective sections.

* Rewrote research questions and objectives in terms of the three main topics in the thesis: Benchmarking, Trajectory Inference, and Network inference. Added overview diagram of which chapters fit in which group.


# Chapter 2: dyngen

* Added more results to this chapter; added detailed use-cases on how to use dyngen to benchmark RNA velocity (written by Wouter Saelens) and Casewise NI methods (written by me). Quantitative evaluation for either of these types of methods is completely novel. A section on using dyngen to benchmark trajectory alignment tools is ongoing but not included in the thesis.

* Expanded the captions of several figures.

* Reworked methods section on module networks and backbones.

* Expanded explanation on how cells are sampled, included an explanatory figure.

* Added use cases for dyngen. Wouter Saelens developed the use case for RNA velocity.

* Added several sections explaining the formulae in table 2.1.

* Added section on code availability.

# Chapter 3: dynbenchmark

* Removed duplicate section on dyngen's methdology.

* Fixed several layout issues.

* Added standalone captions for supplementary files that were not included in the chapter (see section 3.5)

# Chapter 9: discussion

* Completely rewrote this section. Instead of being a summary of the thesis, the discussion now discusses the impact of the work presented and ongoing developments in computational methods for single-cell omics.

# Backmatter

* Expanded curriculum vitae by listing conferences, oral presentations, poster presentations and master student supervisions.

* Added acknowledgement section.
